language: java
jdk: openjdk8

branches:
  only:
  - source

notifications:
  email:
  - anton@galiglobal.com

before_install:
  - true

install:
  - true

script:
  - gradle jbake

before_deploy:
  - true

deploy:
  - true

after_deploy:
  - true

after_script:
  - true
