# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- about_me
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics: UA-57796882-1
favicon: /favicon.png
twitter: 
google_plus:
fb_admins:
fb_app_id:
